issue/#87 chore : temporariesテーブルとモデル削除
NODASHUSEINANODA/ohana_api pull request #103
Opened 2023-07-09 12:55 UTC by Yuki-Miyagi

## チケットへのリンク

* #87 

## やったこと

* temporarisテーブルの削除
* temporaryモデルの削除

## できるようになること（ユーザ目線）

* 何ができるようになるのか？（あれば。無いなら「無し」でOK）

## できなくなること（ユーザ目線）

* 何ができなくなるのか？（あれば。無いなら「無し」でOK）

## 動作確認

* `rails db migrate:reset`でtemporariesテーブルが作られないか確認

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2023-07-10 14:11 UTC, tamashiro-syuta requested changes
@Yuki-Miyagi 
レビューしたよー！！！

2023-07-10 14:11 UTC, tamashiro-syuta commented on db/migrate/20230506125917_create_temporaries.rb
このmigrateファイルは消さないで大丈夫だよー！

`rails db:migrate:reset`したけど、以下のエラーが出た！
```
(略)
== 20230709125019 DropTableTemporaries: migrating =============================
-- drop_table(:temporaries)
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Unknown table 'app_development.temporaries'
/app/db/migrate/20230709125019_drop_table_temporaries.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown table 'app_development.temporaries'
/app/db/migrate/20230709125019_drop_table_temporaries.rb:3:in `change'

Caused by:
Mysql2::Error: Unknown table 'app_development.temporaries'
/app/db/migrate/20230709125019_drop_table_temporaries.rb:3:in `change'
Tasks: TOP => db:migrate:reset => db:migrate
(See full trace by running task with --trace)
```

`rails db:migrate:reset`は、DB情報をリセットしてmigrateファイルを上から逐次実行していくコマンド。
`db/migrate/20230506125917_create_temporaries.rb`を削除すると、`db/migrate/20230709125019_drop_table_temporaries.rb`でdropで指定しているテーブルの`temporaries`なんて知らないよって言われていると思われる！

migrateファイルは触らずに、追加して直していくのが基本！(だから、rubocopで修正するプルリクでもmigrateファイルはrubocopで修正しなかった)

2023-07-11 12:49 UTC, Yuki-Miyagi commented
@tamashiro-syuta お願いします！！！

2023-07-12 13:02 UTC, tamashiro-syuta approved these changes
![LGTM](https://images.lgtmgen.org/12bc4a17-2c69-41a9-880b-8d7544210526)

2023-07-12 13:03 UTC, merged