issue/#182 feat : 翌々月の誕生を次回の注文にセットする
NODASHUSEINANODA/ohana_api pull request #183
Opened 2023-10-24 13:45 UTC by Yuki-Miyagi

## チケットへのリンク

* close #182 

## やったこと

* 翌々月の誕生を次回の注文にセットする

## やらないこと

* このプルリクでやらないことは何か？（あれば。無いなら「無し」でOK）（やらない場合は、いつやるのかを明記する。）

## できるようになること（ユーザ目線）

* 何ができるようになるのか？（あれば。無いなら「無し」でOK）

## できなくなること（ユーザ目線）

* 何ができなくなるのか？（あれば。無いなら「無し」でOK）

## 動作確認

* 翌々月の誕生を次回の注文にセットされている

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2023-10-24 13:45 UTC, Yuki-Miyagi commented
@tamashiro-syuta オネシャス！

2023-10-25 04:41 UTC, tamashiro-syuta requested changes
ごめん、コメントの箇所の修正お願いしますー！！🙏

2023-10-25 04:41 UTC, tamashiro-syuta commented on app/models/company.rb
>    def employees_with_birthdays_next_month
@Yuki-Miyagi 
ごめん、これは俺が実装した箇所だから俺の過失なんだけど、以下の箇所の修正をお願いしたい！！

Companyモデルの`employees_with_birthdays_next_month`メソッドを削除して、呼び出し箇所( `setup_next_order`メソッド )で直接、scopeを呼び出す形に変更して欲しい！(理由はメソッドの内容がemployeeにのみ関する処理でCompanyモデルに書くべき処理じゃないから )

```
birthday_employee_ids = employees.birthday_within_two_months_later.pluck(:id)
```

2023-10-27 16:08 UTC, Yuki-Miyagi commented on app/models/company.rb
>    def employees_with_birthdays_next_month
@tamashiro-syuta 対応完了しました！確認お願いします。
なんか今になって少し他にもリファクタできそうな箇所がありそうだなと思いつつ、開発リソース枯渇しすぎてるから厳しい、、、

2023-10-28 09:12 UTC, tamashiro-syuta approved these changes
![LGTM](https://images.lgtmgen.org/00f2fa8d-7c17-48fa-b714-d987f5cfd090)

2023-10-28 09:13 UTC, tamashiro-syuta commented on app/models/company.rb
>    def employees_with_birthdays_next_month
> なんか今になって少し他にもリファクタできそうな箇所がありそうだなと思いつつ、開発リソース枯渇しすぎてるから厳しい、、、

それな、全部がリファクタできる箇所に見えてきているww

2023-10-28 09:14 UTC, merged