#186 feat : 注文メールのccに会社のアカウントを追加
NODASHUSEINANODA/ohana_api pull request #188
Opened 2023-11-02 14:06 UTC by Yuki-Miyagi

## チケットへのリンク

* close #186 

## やったこと

* 注文メールのccに会社のメールを追加

## やらないこと

* このプルリクでやらないことは何か？（あれば。無いなら「無し」でOK）（やらない場合は、いつやるのかを明記する。）

## できるようになること（ユーザ目線）

* 何ができるようになるのか？（あれば。無いなら「無し」でOK）

## できなくなること（ユーザ目線）

* 何ができなくなるのか？（あれば。無いなら「無し」でOK）

## 動作確認

* どのような動作確認を行ったのか？　結果はどうか？

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2023-11-02 14:09 UTC, Yuki-Miyagi commented
お手隙で確認オネシャス

2023-11-03 13:11 UTC, tamashiro-syuta requested changes
@Yuki-Miyagi 
実装、ありがとう！！
レビューした！！コメント箇所、確認お願いします！！

2023-11-03 13:11 UTC, tamashiro-syuta commented on app/mailers/order_mailer.rb
> +      cc: @company_and_manager_emails,
@Yuki-Miyagi 
> 社長や管理者をメンバーとして登録しなかった場合でも注文メールは会社宛に届くようにしたいから

野田くんが言ってたこと的に、toに会社のアドレス、ccに社長含む管理者とした方が適切だと思う！(社長を登録していない場合にエラーになる)

2023-11-05 12:59 UTC, Yuki-Miyagi commented on app/mailers/order_mailer.rb
> +      cc: @company_and_manager_emails,
ありがとう。まとめて対応します！

2023-11-05 13:58 UTC, Yuki-Miyagi commented
@tamashiro-syuta 確認オネシャス！手元で確認できています！

2023-11-18 04:04 UTC, tamashiro-syuta approved these changes
<img src="https://images.lgtmgen.org/00eb029b-1dee-42e9-acd2-3e833ca21ae5" alt="LGTM" />

2023-11-18 04:05 UTC, tamashiro-syuta commented
@Yuki-Miyagi 
ごめん、めっちゃ遅れた！
スーパー完璧です！！

お手隙でデプロイもしちゃってOKかと！！

2023-11-18 04:05 UTC, merged

2023-11-18 04:21 UTC, Yuki-Miyagi commented
@tamashiro-syuta ごめん、これって、stagingブランチにマージして、確認はしてる？
それとも、普通にmainにマージしただけ？？

2023-11-19 06:08 UTC, tamashiro-syuta commented
@Yuki-Miyagi 

> ごめん、これって、stagingブランチにマージして、確認はしてる？ 
それとも、普通にmainにマージしただけ？？

ごめん、mainにマージしただけでstagingでは確認していない！mm ><