Issue/#20 ログインの基本実装
NODASHUSEINANODA/ohana_api pull request #23
Opened 2023-04-07 14:42 UTC by Yuki-Miyagi

## チケットへのリンク

* close #20 

## やったこと

* sign_up, sign_in, などログイン機能を`devise_token_auth`を用いて実装

## やらないこと

* なし

## できるようになること（ユーザ目線）

* sign_up, sign_inなどのログイン関連の一連の処理

## できなくなること（ユーザ目線）

* 特になし

## 動作確認

1. companyテーブルのカラムなど大きく変更し、新しく作り直したのでもう一でmigrateを実行してほしい。
2. ※注意として、そのままmigrateするとcompanyテーブルがないと怒られるので、最初に`20230402142423_devise_token_auth_create_companies`migrationファイルから実行してほしい。（もしかしたら、先にresetとcreateもしないといけないかも。）
3. `docker-compose run web rails db:migrate;`
4. migrateが成功したら、以下のコマンドを実行して、200okが返ってくるか確認してほしい。

* `curl localhost:3000/auth -X POST -d '{"name":"ohana","email":"test@example.com", "address":"福井市", "password":"password", "password_confirmation": "password", "confirm_success_url":"https://google.com"}' -H "content-type:application/json" -i;`

# ちなみに
[Gmail設定](https://zenn.dev/shogo_matsumoto/articles/c6485b39c5f621#8.-gmail-%E3%81%AE%E3%83%A1%E3%83%BC%E3%83%AB%E3%82%A2%E3%83%97%E3%83%AA%E3%83%91%E3%82%B9%E3%83%AF%E3%83%BC%E3%83%89%E3%82%92%E5%8F%96%E5%BE%97)
をすると自分のメールアドレスにcofirmが届く。

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2023-04-07 14:43 UTC, Yuki-Miyagi commented
@tamashiro-syuta @NODASHUSEINANODA お疲れ！とりあえず、動作確認してほしい。

2023-04-08 03:17 UTC, tamashiro-syuta requested changes

2023-04-08 03:17 UTC, tamashiro-syuta commented on db/migrate/20230311065937_create_companies.rb
migrationファイル消すのはあんまりよくないかも！
`rails db:migrate:reset`したら、以下のエラーが出た。上から順に実行して、migrateが成功するようにした方が良いと思う。デプロイする時も、初回は上から順にmigration実行すると思うから、その時に同じエラーが出るはず。

`db/migrate/20230311065945_create_employees.rb`で存在しないcompanyテーブルにリファレンス貼ってるので、エラーになってるっぽい。
```
Mysql2::Error: Table 'app_development.companies' doesn't exist
/app/db/migrate/20230311065945_create_employees.rb:3:in `change'
```

いろんなところでemployeeを参照しているテーブルあるから、先に`db/migrate/20230402142423_devise_token_auth_create_companies.rb`が一番上に来るようにmigrationファイルを編集した方がいいと思う！(devise以外のファイルを一旦削除して、新しくmigrationファイルを生成して、そこにまたテーブルを作成する処理を書くイメージ)

2023-04-08 03:17 UTC, tamashiro-syuta commented on app/controllers/auth/sessions_controller.rb
current_userがいないパターンの時は、401でエラーで返してもらえるとありがたい！(front側でエラーとしてキャッチして、その旨、表示したいので！)

ざっくり、以下のコードのイメージ！
```
def index
  render json: {is_login: true, data: current_user } if current_user
  render json: {is_login: false, message: "ユーザーが存在しません"}, status: 401
end
```

2023-04-08 03:26 UTC, Yuki-Miyagi commented on db/migrate/20230311065937_create_companies.rb
@tamashiro-syuta なるほど、りょーかいした！

2023-04-08 03:26 UTC, Yuki-Miyagi commented on app/controllers/auth/sessions_controller.rb
@tamashiro-syuta あざす！

2023-04-08 03:36 UTC, tamashiro-syuta commented
プルリクマージしたので、mainブランチをpullして、コンフリクトの解消もお願いしたい >< 🙏 

`git pull origin main`で、エラーなったら、` git config pull.rebase false`でpullできるようになったはず(多分)

2023-04-08 15:50 UTC, Yuki-Miyagi commented
@tamashiro-syuta レビューいただいところを直したのと、issue/#20で最新化したローカルmainブランチをmergeしてconflict直してみたけど、解消されているよね・・

2023-04-14 12:58 UTC, tamashiro-syuta approved these changes
完璧〜〜！！！

![LGTM](https://images.lgtmgen.org/cdccba77-b180-4e8f-9af0-38aeeffa8791)

2023-04-14 13:26 UTC, tamashiro-syuta commented
いい感じだから、マージするね！

2023-04-14 13:26 UTC, merged